export const TIME_FORMAT_PATTERNS = {
  TWELVE_HOURS_WITH_ZERO: 'hh',
  TWELVE_HOURS_WITHOUT_ZERO: 'h',
  TWENTY_FOUR_HOURS_WITH_ZERO: 'HH',
  TWENTY_FOUR_HOURS_WITHOUT_ZERO: 'H',
  MINUTES_WITH_ZERO: 'mm',
  MINUTES_WITHOUT_ZERO: 'm',
  SECONDS_WITH_ZERO: 'ss',
  SECONDS_WITHOUT_ZERO: 's',
  PERIOD_OF_DAY: 'tt',
  AM: 'AM',
  PM: 'PM',
  DEFAULT_TIME_FORMAT: 'hh:mm:ss tt'
};